# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdx/edge/v1/edge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gdx/edge/v1/edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gdx.common.v1 import types_pb2 as gdx_dot_common_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gdx/edge/v1/edge.proto\x12\x0bgdx.edge.v1\x1a\x19gdx/common/v1/types.proto\"\xd2\x01\n\x0bOrderHeader\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x11\n\tsymbol_id\x18\x02 \x01(\x04\x12\x30\n\x0crequest_type\x18\x03 \x01(\x0e\x32\x1a.gdx.common.v1.RequestType\x12\r\n\x05nonce\x18\x04 \x01(\x04\x12\x13\n\x0b\x62ody_length\x18\x05 \x01(\r\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\x0c\x12\x0f\n\x07\x63onn_id\x18\x07 \x01(\x04\x12\x17\n\x0f\x65\x64ge_ingress_at\x18\x08 \x01(\x04J\x05\x08\x64\x10\xc8\x01\"p\n\x14\x45ncryptedEdgeRequest\x12\x0f\n\x07version\x18\x01 \x01(\r\x12(\n\x06header\x18\x02 \x01(\x0b\x32\x18.gdx.edge.v1.OrderHeader\x12\x16\n\x0e\x65ncrypted_body\x18\x03 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"\xdd\x01\n\x0eResponseHeader\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x38\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\".gdx.common.v1.ResponseMessageType\x12\x13\n\x0b\x62ody_length\x18\x03 \x01(\r\x12\r\n\x05nonce\x18\x04 \x01(\x04\x12\x15\n\rfencing_epoch\x18\x05 \x01(\x04\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\x0c\x12\x13\n\x0bsession_seq\x18\x07 \x01(\x04\x12\x0f\n\x07\x63onn_id\x18\x08 \x01(\x04J\x05\x08\x64\x10\xc8\x01\"t\n\x15\x45ncryptedEdgeResponse\x12\x0f\n\x07version\x18\x01 \x01(\r\x12+\n\x06header\x18\x02 \x01(\x0b\x32\x1b.gdx.edge.v1.ResponseHeader\x12\x16\n\x0e\x65ncrypted_body\x18\x03 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"1\n\x0eSessionControl\x12\x18\n\x10last_applied_seq\x18\x01 \x01(\x04J\x05\x08\x64\x10\xc8\x01\"E\n\x0eNoiseHandshake\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63onn_id\x18\x02 \x01(\x04\x12\x0f\n\x07message\x18\x03 \x01(\x0c\"L\n\x13NoiseHandshakeReply\x12\x0f\n\x07\x63onn_id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65stablished\x18\x03 \x01(\x08\"2\n\x0cSessionClose\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63onn_id\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdx.edge.v1.edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERHEADER']._serialized_start=67
  _globals['_ORDERHEADER']._serialized_end=277
  _globals['_ENCRYPTEDEDGEREQUEST']._serialized_start=279
  _globals['_ENCRYPTEDEDGEREQUEST']._serialized_end=391
  _globals['_RESPONSEHEADER']._serialized_start=394
  _globals['_RESPONSEHEADER']._serialized_end=615
  _globals['_ENCRYPTEDEDGERESPONSE']._serialized_start=617
  _globals['_ENCRYPTEDEDGERESPONSE']._serialized_end=733
  _globals['_SESSIONCONTROL']._serialized_start=735
  _globals['_SESSIONCONTROL']._serialized_end=784
  _globals['_NOISEHANDSHAKE']._serialized_start=786
  _globals['_NOISEHANDSHAKE']._serialized_end=855
  _globals['_NOISEHANDSHAKEREPLY']._serialized_start=857
  _globals['_NOISEHANDSHAKEREPLY']._serialized_end=933
  _globals['_SESSIONCLOSE']._serialized_start=935
  _globals['_SESSIONCLOSE']._serialized_end=985
# @@protoc_insertion_point(module_scope)
