# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdx/edge/v1/edge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdx/edge/v1/edge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gdx.common.v1 import types_pb2 as gdx_dot_common_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gdx/edge/v1/edge.proto\x12\x0bgdx.edge.v1\x1a\x19gdx/common/v1/types.proto\"\xa8\x01\n\x0bOrderHeader\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x11\n\tsymbol_id\x18\x02 \x01(\x04\x12\x30\n\x0crequest_type\x18\x03 \x01(\x0e\x32\x1a.gdx.common.v1.RequestType\x12\r\n\x05nonce\x18\x04 \x01(\x04\x12\x13\n\x0b\x62ody_length\x18\x05 \x01(\r\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"p\n\x14\x45ncryptedEdgeRequest\x12\x0f\n\x07version\x18\x01 \x01(\r\x12(\n\x06header\x18\x02 \x01(\x0b\x32\x18.gdx.edge.v1.OrderHeader\x12\x16\n\x0e\x65ncrypted_body\x18\x03 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"\x9f\x01\n\x0eResponseHeader\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x38\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\".gdx.common.v1.ResponseMessageType\x12\x13\n\x0b\x62ody_length\x18\x03 \x01(\r\x12\r\n\x05nonce\x18\x04 \x01(\x04\x12\x15\n\rfencing_epoch\x18\x05 \x01(\x04J\x05\x08\x64\x10\xc8\x01\"t\n\x15\x45ncryptedEdgeResponse\x12\x0f\n\x07version\x18\x01 \x01(\r\x12+\n\x06header\x18\x02 \x01(\x0b\x32\x1b.gdx.edge.v1.ResponseHeader\x12\x16\n\x0e\x65ncrypted_body\x18\x03 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"D\n\x0cSessionSetup\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x1a\n\x12\x63lient_ecdh_pubkey\x18\x02 \x01(\x0cJ\x05\x08\x64\x10\xc8\x01\"N\n\x12SessionEstablished\x12\x1d\n\x15sequencer_ecdh_pubkey\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\x04J\x05\x08\x64\x10\xc8\x01\"=\n\rRekeyRequired\x12\x11\n\tuser_uuid\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\x04J\x05\x08\x64\x10\xc8\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdx.edge.v1.edge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERHEADER']._serialized_start=67
  _globals['_ORDERHEADER']._serialized_end=235
  _globals['_ENCRYPTEDEDGEREQUEST']._serialized_start=237
  _globals['_ENCRYPTEDEDGEREQUEST']._serialized_end=349
  _globals['_RESPONSEHEADER']._serialized_start=352
  _globals['_RESPONSEHEADER']._serialized_end=511
  _globals['_ENCRYPTEDEDGERESPONSE']._serialized_start=513
  _globals['_ENCRYPTEDEDGERESPONSE']._serialized_end=629
  _globals['_SESSIONSETUP']._serialized_start=631
  _globals['_SESSIONSETUP']._serialized_end=699
  _globals['_SESSIONESTABLISHED']._serialized_start=701
  _globals['_SESSIONESTABLISHED']._serialized_end=779
  _globals['_REKEYREQUIRED']._serialized_start=781
  _globals['_REKEYREQUIRED']._serialized_end=842
# @@protoc_insertion_point(module_scope)
